package model;
// Generated May 10, 2016 4:33:10 PM by Hibernate Tools 4.3.1



/**
 * Photo generated by hbm2java
 */
public class Photo  implements java.io.Serializable {


     private Integer idPhoto;
     private Integer idMember;
     private String title;
     private String topic;
     private Integer totalView;
     private Integer totalLike;
     private byte[] photoSrc;

    public Photo() {
       this.title = "test";
    }

    public Photo(Integer idMember, String title, String topic, Integer totalView, Integer totalLike, byte[] photoSrc) {
       this.idMember = idMember;
       this.title = title;
       this.topic = topic;
       this.totalView = totalView;
       this.totalLike = totalLike;
       this.photoSrc = photoSrc;
    }
   
    public Integer getIdPhoto() {
        return this.idPhoto;
    }
    
    public void setIdPhoto(Integer idPhoto) {
        this.idPhoto = idPhoto;
    }
    public Integer getIdMember() {
        return this.idMember;
    }
    
    public void setIdMember(Integer idMember) {
        this.idMember = idMember;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public Integer getTotalView() {
        return this.totalView;
    }
    
    public void setTotalView(Integer totalView) {
        this.totalView = totalView;
    }
    public Integer getTotalLike() {
        return this.totalLike;
    }
    
    public void setTotalLike(Integer totalLike) {
        this.totalLike = totalLike;
    }
    public byte[] getPhotoSrc() {
        return this.photoSrc;
    }
    
    public void setPhotoSrc(byte[] photoSrc) {
        this.photoSrc = photoSrc;
    }




}


