package model;
// Generated May 6, 2016 11:31:26 AM by Hibernate Tools 4.3.1



/**
 * TblMember generated by hbm2java
 */
public class TblMember  implements java.io.Serializable {


     private int idMember;
     private String nickname;
     private String passwork;
     private String fullname;
     private String email;
     private String gender;
     private String accessadmin;

    public TblMember() {
    }

	
    public TblMember(int idMember) {
        this.idMember = idMember;
    }
    public TblMember(int idMember, String nickname, String passwork, String fullname, String email, String gender, String accessadmin) {
       this.idMember = idMember;
       this.nickname = nickname;
       this.passwork = passwork;
       this.fullname = fullname;
       this.email = email;
       this.gender = gender;
       this.accessadmin = accessadmin;
    }
   
    public int getIdMember() {
        return this.idMember;
    }
    
    public void setIdMember(int idMember) {
        this.idMember = idMember;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getPasswork() {
        return this.passwork;
    }
    
    public void setPasswork(String passwork) {
        this.passwork = passwork;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAccessadmin() {
        return this.accessadmin;
    }
    
    public void setAccessadmin(String accessadmin) {
        this.accessadmin = accessadmin;
    }




}


